// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
import { integer, real, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";
export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull().unique(),name:text("name"),role:text("role",{enum:["traveller","operator","admin"]}).notNull().default("traveller"),createdAt:integer("created_at").notNull()});
export const listings=sqliteTable("listings",{id:text("id").primaryKey(),operatorId:text("operator_id"),from:text("from").notNull(),fromCode:text("from_code").notNull(),to:text("to").notNull(),toCode:text("to_code").notNull(),departureAt:text("departure_at").notNull(),aircraft:text("aircraft").notNull(),seats:integer("seats").notNull(),price:real("price").notNull(),status:text("status").notNull().default("live"),createdAt:integer("created_at").notNull(),source:text("source").notNull().default("operator"),sourceId:text("source_id"),currency:text("currency").notNull().default("EUR"),arrivalAt:text("arrival_at"),tailNumber:text("tail_number"),lastSeenAt:integer("last_seen_at"),updatedAt:integer("updated_at"),fromLat:real("from_lat"),fromLng:real("from_lng"),toLat:real("to_lat"),toLng:real("to_lng")},t=>[index("idx_listings_live_departure").on(t.status,t.departureAt),uniqueIndex("idx_listings_source_id").on(t.source,t.operatorId,t.sourceId)]);
export const alerts=sqliteTable("alerts",{id:text("id").primaryKey(),userId:text("user_id").notNull(),fromCode:text("from_code"),toCode:text("to_code"),maxPrice:real("max_price"),minSeats:integer("min_seats").default(1),active:integer("active",{mode:"boolean"}).default(true)});
export const bookings=sqliteTable("bookings",{id:text("id").primaryKey(),listingId:text("listing_id").notNull(),userId:text("user_id").notNull(),amount:real("amount").notNull(),stripeSessionId:text("stripe_session_id"),status:text("status").notNull().default("pending"),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_bookings_listing_user").on(t.listingId,t.userId)]);
export const sourceSyncs=sqliteTable("source_syncs",{id:text("id").primaryKey(),provider:text("provider").notNull(),lastSuccessAt:integer("last_success_at"),lastAttemptAt:integer("last_attempt_at"),lastError:text("last_error"),importedCount:integer("imported_count").notNull().default(0)});
export const alertMatches=sqliteTable("alert_matches",{id:text("id").primaryKey(),alertId:text("alert_id").notNull(),listingId:text("listing_id").notNull(),createdAt:integer("created_at").notNull(),deliveryStatus:text("delivery_status").notNull().default("pending")},t=>[uniqueIndex("idx_alert_matches_alert_listing").on(t.alertId,t.listingId)]);
export {};
